"""Phase 9 delivery tests: the documents must describe this system, not a memory of it.

Documentation drift is invisible by construction. A number changes, the prose
does not, and the prose is what a reviewer reads and trusts. So the claims the
delivery documents make are asserted here, against the live pipeline and the
live data files.

This is deliberately not a spell-check or a link-checker. It checks the specific
numbers a reader would act on: the test count, the eval headline, the chunk
count, the number of sources, and whether the disclaimer in `docs/` is the same
bytes as the disclaimer the code returns.
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import pytest

import common

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

DELIVERABLES = [
    ROOT / "README.md",
    DOCS / "SOURCES.md",
    DOCS / "SOURCES.csv",
    DOCS / "SAMPLE_QA.md",
    DOCS / "DISCLAIMER.md",
    ROOT / "eval" / "report.md",
    ROOT / "PRD.md",
    DOCS / "architecture.md",
    DOCS / "implementation.md",
]


@pytest.mark.parametrize("path", DELIVERABLES, ids=lambda p: p.name)
def test_the_deliverable_exists_and_is_not_empty(path):
    assert path.exists(), f"{path.relative_to(ROOT)} is missing"
    assert path.stat().st_size > 400, f"{path.name} is suspiciously small"


# ---------------------------------------------------------------------------
# The disclaimer: one string, one set of bytes
# ---------------------------------------------------------------------------


def test_the_disclaimer_doc_holds_the_disclaimer_byte_for_byte():
    """A second, hand-typed copy of a compliance string is a copy that drifts.

    `docs/DISCLAIMER.md` is generated by `tools/make_disclaimer.py`, and this
    asserts the generation did not quietly mangle it - a stray markdown escape
    or a reflowed line would both make the file *look* right.
    """
    from rag.guardrails import DISCLAIMER

    text = (DOCS / "DISCLAIMER.md").read_text(encoding="utf-8")
    assert DISCLAIMER in text, "docs/DISCLAIMER.md does not contain the exact string"
    assert text.count(DISCLAIMER) == 1, "the disclaimer appears more than once"


def test_the_disclaimer_is_the_prd_one():
    """PRD §11 fixes the wording. The code must not have quietly edited it."""
    from rag.guardrails import DISCLAIMER

    prd = (ROOT / "PRD.md").read_text(encoding="utf-8")
    assert DISCLAIMER in prd, "the code's disclaimer no longer matches PRD §11"


def test_every_answer_carries_the_disclaimer_verbatim():
    from rag.answer import ask
    from rag.guardrails import DISCLAIMER

    for q in ("What is the expense ratio of HDFC Large Cap Direct Growth?",
              "Should I buy HDFC Large Cap Fund?"):
        a = ask(q)
        assert a.disclaimer == DISCLAIMER, q


# ---------------------------------------------------------------------------
# Sample Q&A: a transcript, so it has to match
# ---------------------------------------------------------------------------


def test_sample_qa_has_between_five_and_ten_questions():
    """The brief asks for 5-10 sample Q&A. Ten covers all five schemes plus
    every refusal path without padding."""
    text = (DOCS / "SAMPLE_QA.md").read_text(encoding="utf-8")
    n = len(re.findall(r"^### \d+\. ", text, re.M))
    assert 5 <= n <= 10, f"{n} questions"


def test_every_source_link_in_sample_qa_is_a_real_corpus_url():
    urls = {c.get("source_url")
            for c in common.read_jsonl(common.path_for("chunks_file"))}
    text = (DOCS / "SAMPLE_QA.md").read_text(encoding="utf-8")
    for u in set(re.findall(r"Source: (https?://\S+)", text)):
        assert u in urls, f"{u} is cited but is not in the corpus"


def test_no_sample_qa_answer_shows_its_source_twice():
    """FR-8.4 is "the one source link".

    The stub appends a bare `Source: <url>` to `Answer.text` for the CLI, so a
    renderer that also prints the citation line shows it twice. This is the
    exact bug the UI hit; the doc would hit it the same way.
    """
    text = (DOCS / "SAMPLE_QA.md").read_text(encoding="utf-8")
    for block in re.findall(r"```\n(.*?)\n```", text, re.S):
        if "Source: http" in block:
            continue  # this is the citation block, which is allowed
        assert "Source: http" not in block, f"source rendered twice: {block[:90]!r}"


def test_every_refusal_in_sample_qa_carries_no_citation():
    """A refusal is a policy response, not a sourced fact."""
    text = (DOCS / "SAMPLE_QA.md").read_text(encoding="utf-8")
    for section in re.split(r"^### \d+\. ", text, flags=re.M)[1:]:
        head = section.split("```")[0]
        if "**`refusal" in head or "**`out_of_corpus" in head or "**`error" in head:
            assert "\nSource: http" not in section, (
                f"a refusal in SAMPLE_QA.md has a citation: {head[:70]!r}")


def test_no_sample_qa_answer_exceeds_three_sentences():
    from rag.guardrails import count_sentences

    text = (DOCS / "SAMPLE_QA.md").read_text(encoding="utf-8")
    checked = 0
    for block in re.findall(r"```\n(.*?)\n```", text, re.S):
        body = common.strip_inline_source(block).strip()
        if not body or body.startswith("Last updated"):
            continue
        n = count_sentences(body)
        assert n <= 3, f"{n} sentences: {body[:90]!r}"
        checked += 1
    assert checked >= 5, "no answer bodies found - the file may have changed shape"


# ---------------------------------------------------------------------------
# Sources
# ---------------------------------------------------------------------------


def test_sources_csv_has_one_row_per_actually_fetched_source():
    """Three things must agree: what `config/sources.yaml` says to fetch, what
    `data/source_snapshot.json` records as fetched, and what SOURCES.csv lists.

    `supplementary` holds 6 entries but only 2 have `fetch: true`. The other 4
    are SEBI/AMFI/HDFC links that exist purely so the refusal hand-off URLs are
    declared somewhere auditable rather than buried in a string literal. They
    are deliberately not fetched, so they are deliberately not in the CSV.
    """
    import yaml

    cfg = yaml.safe_load((ROOT / "config" / "sources.yaml").read_text(encoding="utf-8"))
    wanted = {s["url"] for s in cfg["schemes"]}
    wanted |= {s["url"] for s in cfg["supplementary"] if s.get("fetch")}

    snap = json.loads((ROOT / "data" / "source_snapshot.json")
                      .read_text(encoding="utf-8"))
    fetched = {v["url"] for k, v in snap.items() if not k.startswith("_")}

    with (DOCS / "SOURCES.csv").open(newline="", encoding="utf-8") as fh:
        listed = {r["url"] for r in csv.DictReader(fh)}

    assert wanted == fetched, f"config vs snapshot: {wanted ^ fetched}"
    assert listed == fetched, f"SOURCES.csv vs snapshot: {listed ^ fetched}"


def test_the_pages_that_were_never_fetched_are_declared_not_just_omitted():
    """A source list that silently drops pages hides a decision. The 4
    `fetch: false` pages must still be declared, so a reviewer can see they
    were considered and rejected rather than overlooked."""
    import yaml

    cfg = yaml.safe_load((ROOT / "config" / "sources.yaml").read_text(encoding="utf-8"))
    never = [s for s in cfg["supplementary"] if not s.get("fetch")]
    assert len(never) == 4
    for s in never:
        assert s.get("url"), f"{s['doc_id']} is declared but has no URL to audit"
        assert s.get("used_for"), f"{s['doc_id']} does not say why it is listed"
    # none of them may be in the corpus
    corpus_urls = {c.get("source_url")
                   for c in common.read_jsonl(common.path_for("chunks_file"))}
    for s in never:
        assert s["url"] not in corpus_urls, f"{s['doc_id']} was never fetched"


def test_the_indexable_page_count_matches_the_chunked_corpus():
    with (DOCS / "SOURCES.csv").open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    indexable = [r for r in rows if r["indexable"] == "yes"]
    assert len(indexable) == 5
    assert sum(int(r["chunks"]) for r in indexable) == len(
        common.read_jsonl(common.path_for("chunks_file")))


def test_no_source_is_a_blog_an_aggregator_or_a_forum():
    """The brief excludes third-party commentary. Seven pages, all named."""
    with (DOCS / "SOURCES.csv").open(newline="", encoding="utf-8") as fh:
        hosts = {re.sub(r"^https?://([^/]+).*$", r"\1", r["url"]) for r in csv.DictReader(fh)}
    assert hosts <= {"groww.in", "www.amfiindia.com"}, hosts


# ---------------------------------------------------------------------------
# README: the numbers a reader would act on
# ---------------------------------------------------------------------------


def test_the_readme_test_count_is_the_real_one():
    """'513 tests' in the README has to match `pytest -q`.

    Counting by collection rather than trusting the README is the only way this
    stays true; a doc test that reads the number out of the doc is worthless.
    """
    import subprocess
    import sys

    out = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q", "--collect-only"],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace",
    ).stdout
    m = re.search(r"(\d+) tests? collected", out)
    if not m:
        m = re.search(r"(\d+) / (\d+)", out)
    assert m, "could not count collected tests"
    total = int(m.group(1)) if m.lastindex and m.lastindex > 1 else int(m.group(1))
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert f"**{total} tests" in readme or f"{total} tests" in readme, (
        f"the README does not state the real test count ({total})")


def test_the_readme_eval_headline_matches_the_recorded_run():
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    s = json.loads((ROOT / "eval" / "results.json").read_text(encoding="utf-8"))["summary"]
    a, r = s["answerable"], s["must_refuse"]
    assert f"{a['n']}/{a['n']} answerable" in readme, f"answerable n={a['n']}"
    assert f"{r['n']}/{r['n']} refused" in readme, f"refuse n={r['n']}"
    assert f"{a['grounded']:.0f}%" in readme, f"grounded={a['grounded']}"


def test_the_readme_chunk_count_is_the_real_one():
    n = len(common.read_jsonl(common.path_for("chunks_file")))
    assert f"{n} chunks" in (ROOT / "README.md").read_text(encoding="utf-8")


def test_the_retrieval_test_count_in_the_readme_is_real():
    import subprocess
    import sys

    out = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/test_retrieval.py", "-q",
         "--collect-only"],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace",
    ).stdout
    m = re.search(r"(\d+) tests? collected", out)
    assert m, out[-400:]
    n = int(m.group(1))
    assert f"{n} of them" in (ROOT / "README.md").read_text(encoding="utf-8"), n


def test_the_readme_documents_a_retrieval_command_that_actually_exists():
    """Every `python -m X` in the README must be a real module with a __main__."""
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    mods = set(re.findall(r"python(?:\.exe)? -m ([\w.]+)", readme))
    # Not project modules: these are invoked through -m but are not part of
    # this codebase. `venv` comes from `python -m venv .venv` in the setup.
    external = {"pip", "pytest", "streamlit", "venv"}
    assert mods - external
    for mod in sorted(mods - external):
        path = ROOT / (mod.replace(".", "/") + ".py")
        assert path.exists(), f"README references {mod}, which does not exist"
        assert "__main__" in path.read_text(encoding="utf-8"), (
            f"README says `python -m {mod}` but it has no __main__ block")


def test_the_readme_never_says_the_demo_has_a_question_count_it_does_not():
    """`rag.retrieve --demo` and `rag.answer --demo` are different sets, and the
    README must not quote the wrong one."""
    import rag.answer as A
    import rag.retrieve as Rt

    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    n_answer = len(A.DEMO_QUESTIONS)
    m = re.search(r"rag\.retrieve --demo.{0,40}?(\d+) questions", readme, re.S)
    if m:
        src = (ROOT / "rag" / "retrieve.py").read_text(encoding="utf-8")
        n_retrieve = len(re.findall(r"^\s+\"[^\"]{10,}\",\s*$",
                                    src, re.M))
        assert int(m.group(1)) == n_retrieve, (
            f"README says the retrieve demo has {m.group(1)} questions")
    assert f"{n_answer}-question" in readme, (
        f"README should state the answer demo's real count ({n_answer})")
