"""Write `docs/SOURCES.md` from the corpus and the fetch snapshot.

Same reasoning as `make_disclaimer.py`: the source list is the artefact a
reviewer checks against the brief, and a hand-typed one drifts from what was
actually fetched. Every URL, node count, chunk count, byte count, SHA-256 and
timestamp below is read out of `data/corpus.jsonl`, `data/chunks.jsonl` and
`data/source_snapshot.json`.

    python -m tools.make_sources
"""

from __future__ import annotations

import collections
import csv
import sys
from pathlib import Path

import common

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "docs" / "SOURCES.md"
CSV = ROOT / "docs" / "SOURCES.csv"

COLUMNS = ["source_id", "url", "title", "publisher", "page_type", "indexable",
           "nodes", "chunks", "fact_keys", "visible_chars", "bytes", "sha256",
           "fetched_at_utc"]


def gather() -> list[dict[str, object]]:
    import json
    import yaml

    corpus = common.read_json(common.path_for("corpus_file"))
    docs = {d.get("source_url"): d for d in corpus.get("documents", [])}

    snap = json.loads((ROOT / "data" / "source_snapshot.json")
                      .read_text(encoding="utf-8"))
    by_url = {v.get("url"): (k, v) for k, v in snap.items() if not k.startswith("_")}

    # Publisher and page_type come from config/sources.yaml, not the snapshot
    cfg = yaml.safe_load((ROOT / "config" / "sources.yaml").read_text(encoding="utf-8"))
    publisher_by_url = {}
    page_type_by_url = {}
    for s in cfg.get("schemes", []) + cfg.get("supplementary", []):
        if s.get("url"):
            publisher_by_url[s["url"]] = s.get("publisher", "")
            page_type_by_url[s["url"]] = s.get("page_type", "")

    chunks = common.read_jsonl(common.path_for("chunks_file"))
    per = collections.Counter(c.get("source_url") for c in chunks)
    keys: dict[str, set[str]] = collections.defaultdict(set)
    for c in chunks:
        if c.get("fact_key"):
            keys[c.get("source_url")].add(c["fact_key"])

    # Only scheme pages reach the corpus gate; the two supplementary pages are
    # fetched every run and rejected, and that rejection is part of the record.
    indexable = {u for u, n in per.items() if n}

    rows: list[dict[str, object]] = []
    for url, (sid, s) in sorted(by_url.items(), key=lambda kv: (-per[kv[0]], kv[0])):
        rows.append({
            "source_id": sid,
            "url": url,
            "title": (docs.get(url) or {}).get("page_title") or "",
            "publisher": publisher_by_url.get(url, s.get("publisher", "")),
            "page_type": page_type_by_url.get(url, s.get("page_type", "")),
            "indexable": "yes" if url in indexable else "no",
            "nodes": (docs.get(url) or {}).get("node_count", ""),
            "chunks": per.get(url, 0),
            "fact_keys": len(keys.get(url, ())),
            "visible_chars": s.get("visible_chars", ""),
            "bytes": s.get("bytes", ""),
            "sha256": s.get("sha256", ""),
            "fetched_at_utc": s.get("fetched_at", ""),
        })
    return rows


def render_md(rows: list[dict[str, object]]) -> str:
    snap = common.read_json(ROOT / "data" / "source_snapshot.json")
    total_chunks = sum(int(r["chunks"]) for r in rows)
    idx = [r for r in rows if r["indexable"] == "yes"]
    L: list[str] = []
    L.append("# Sources\n")
    L.append(f"All {len(rows)} pages were fetched on **{snap['_updated_at']}**. "
             f"Generated by `python -m tools.make_sources`; the same table is in "
             f"`docs/SOURCES.csv` for a spreadsheet.\n")

    L.append("## What is in scope\n")
    L.append(f"The corpus is **{len(idx)} indexable pages** - the AMC's own page "
             f"for each of the five schemes, plus its consolidated account "
             f"statement page, which is where the statement-download and "
             f"capital-gains answers come from - totalling **{total_chunks} "
             f"chunks**. The other {len(rows) - len(idx)} pages are fetched on "
             "every run and then rejected by the Stage 2 corpus gate: they are "
             "listed below because a source list that hid them would not be a "
             "source list.\n")

    L.append("| Scheme | Publisher | Chunks | Fact keys |")
    L.append("|---|---|---|---|")
    for r in idx:
        title = str(r["title"]) or str(r["source_id"])
        # the page title carries a long SEO suffix; the scheme name is cleaner
        name = title.split(" - ")[0] if " - " in title else title
        L.append(f"| [{name}]({r['url']}) | {r['publisher']} | "
                 f"{r['chunks']} | {r['fact_keys']} |")
    L.append(f"| **Total** | | **{total_chunks}** | |")
    L.append("")

    L.append("## Full fetch record\n")
    L.append("`sha256` is the SHA-256 of the raw bytes as fetched, so any later "
             "change to a page is detectable. `visible_chars` is the character "
             "count of the extracted visible text, which is what the chunker "
             "actually sees.\n")
    L.append("| source_id | Publisher | Type | In corpus | Nodes | Chunks | "
             "Visible chars | Bytes | SHA-256 (first 16) | Fetched (UTC) |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        L.append(f"| `{r['source_id']}` | {r['publisher']} | {r['page_type']} | "
                 f"{r['indexable']} | {r['nodes']} | {r['chunks']} | "
                 f"{r['visible_chars']} | {r['bytes']} | "
                 f"`{str(r['sha256'])[:16]}` | {r['fetched_at_utc']} |")
    L.append("")

    L.append(f"## The {len(rows) - len(idx)} pages that were fetched but rejected\n")
    L.append("Both are legitimate sources - an AMC-licensed body and the "
             "broker's own help centre - and both are excluded for the same "
             "reason: neither is about one of the five schemes. The gate is in "
             "`config/sources.yaml` and runs on every ingest, so this is a "
             "decision the pipeline re-makes rather than a one-time cleanup.\n")
    for r in rows:
        if r["indexable"] == "yes":
            continue
        L.append(f"- **[{r['title'] or r['source_id']}]({r['url']})** "
                 f"({r['publisher']}, {r['visible_chars']} visible chars) - not a "
                 f"`scheme_page`, so it is fetched for the record and not indexed.")
    L.append("")

    L.extend(_never_fetched())

    L.append("## Sourcing rules the pipeline enforces\n")
    L.append("These are not guidelines the author followed; each one is a check "
             "in code with a test behind it.\n")
    L.append("- **Only the URLs in `config/sources.yaml` are ever fetched.** "
             "There is no crawler and no link-following, so the corpus cannot "
             "grow beyond the seven pages above by accident.")
    L.append("- **Publisher is recorded per chunk**, and every chunk resolves to "
             "Groww. The refusal texts point at SEBI and AMFI's investor-"
             "education material, which is deliberately *not* in the corpus - "
             "those are hand-offs, not citations.")
    L.append("- **No third-party blog, aggregator or forum is a source.** The "
             "brief excludes them, and the list above is short enough to check by "
             "eye: two domains, `groww.in` and `amfiindia.com`.")
    L.append("- **Every figure is quoted, never derived.** No ratio, no return, "
             "no ranking between schemes is computed anywhere in the pipeline. "
             "The one figure that looks like an exception is in the corpus "
             "itself: one FAQ chunk on the page states the fund's average "
             "annual return since inception is 18.28%, and `rag/guardrails.py` "
             "refuses that number even though the page publishes it, because "
             "reporting it is a performance claim regardless of where it came "
             "from.")
    L.append("- **Fetch date is carried on every chunk**, which is what makes the "
             "`Last updated from sources: YYYY-MM-DD` stamp on an answer "
             "truthful rather than decorative.")
    L.append("")

    L.append("## Refreshing\n")
    L.append(f"```\npython -m ingest.fetch --force   # re-fetch all {len(rows)} pages\n"
             "python -m tools.dump               # refresh data/dump/*.txt\n"
             "python -m tools.make_sources       # regenerate this file + the CSV\n```")
    L.append("")
    L.append("A NAV or an AUM on these pages changes without notice, so a demo run "
             "on a stale snapshot will quote figures that have moved. "
             "The stamp is there so that is visible rather than hidden.\n")
    return "\n".join(L)


def _never_fetched() -> list[str]:
    """The `fetch: false` supplementary pages.

    Four URLs sit in `config/sources.yaml` that are never fetched: SEBI's
    riskometer explainer, SEBI and AMFI's investor-education pages, and HDFC
    AMC's own FAQ. They are listed so the hand-off URLs a refusal points at are
    declared somewhere a reviewer can audit them, rather than buried in a string
    literal. Their absence from the fetch record is deliberate.
    """
    import yaml

    cfg = yaml.safe_load((ROOT / "config" / "sources.yaml")
                         .read_text(encoding="utf-8"))
    never = [s for s in (cfg.get("supplementary") or []) if not s.get("fetch")]
    if not never:
        return []
    L = [f"## The {len(never)} pages that were never fetched\n",
         "Declared in `config/sources.yaml` with `fetch: false`, and absent from "
         "the fetch record on purpose. They are here so that every URL this "
         "assistant can point a user at is written down somewhere - a refusal "
         "that hands over to SEBI's investor-education material should not do "
         "so via a link buried in a string literal. None of them is in the "
         "corpus, and a test asserts that.\n",
         "| Publisher | Page | Why it is listed |", "|---|---|---|"]
    for s in never:
        L.append(f"| {s.get('publisher', '')} | "
                 f"[{s.get('title') or s.get('doc_id')}]({s.get('url')}) | "
                 f"{s.get('used_for', '')} |")
    L.append("")
    return L


def main() -> int:
    rows = gather()
    MD.write_text(render_md(rows), encoding="utf-8")
    with CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {MD.relative_to(ROOT)} and {CSV.relative_to(ROOT)} ({len(rows)} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
