"""Write `docs/DISCLAIMER.md` with the disclaimer copied, not retyped.

The disclaimer is a compliance artefact. A hand-typed copy in a second file is
a copy that can drift, and a drifted disclaimer is worse than none, because
everything around it still looks correct. So the string is imported from
`rag.guardrails.DISCLAIMER` - the same object the UI and every answer use - and
`tests/test_delivery.py` asserts the document contains it byte for byte.

    python -m tools.make_disclaimer
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DISCLAIMER.md"

PREAMBLE = """# Disclaimer

The text below is the disclaimer, verbatim. It is not a summary of it and not a
paraphrase of it.

It is generated by `python -m tools.make_disclaimer` from
`rag.guardrails.DISCLAIMER`, which is the same string PRD §11 fixes and the same
object attached to every `Answer` the pipeline returns and rendered by
`app.py`. There is exactly one copy in the system; this file is a copy *of* that
one, produced mechanically.

## Where it appears

| Where | How |
|---|---|
| Every answer, in the UI | `app.py` renders `G.DISCLAIMER` under the answer |
| Every answer, from the CLI | `rag/answer.py` sets `Answer.disclaimer` |
| Every answer, in the generated Q&A | `docs/SAMPLE_QA.md` |
| The eval report | `eval/run_eval.py` records `disclaimer_ok` per row |

## The disclaimer

"""

POSTAMBLE = """

## How to read it

Three of its sentences are load-bearing, and each rules out a specific thing
this assistant is built not to do.

**"It does not recommend, compare, or rate schemes."** The corpus contains all
five schemes' expense ratios, so it could rank them by cost - and that ranking
would be a recommendation, because a cheaper TER is the reason a person often
picks a scheme. The numbers are available; the comparison is withheld.

**"It does not compute or report returns."** A return needs a start date, an end
date and a price source, and choosing them is an act of authority. The refusal
text hands over to the published factsheet instead, which has that authority.

**"read all scheme-related documents carefully."** Not boilerplate. The corpus is
121 chunks scraped from five web pages, and a scraped page is a snapshot: it can
be stale, and it is not the scheme's own document. The dated
`Last updated from sources:` stamp on every answer exists so a reader can see
how old the snapshot is, and this sentence is why the stamp is there.
"""


def main() -> int:
    from rag.guardrails import DISCLAIMER

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(PREAMBLE + DISCLAIMER + POSTAMBLE, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes, "
          f"disclaimer {len(DISCLAIMER)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
